In [1]:
github.com/saketh-26/machinelearningwithpython

NameError: name 'github' is not defined

In [2]:
#element accessing row/column
#loc and iloc.......>location and index location based

In [3]:
import pandas as pd

In [5]:
df=pd.DataFrame({"name":['vasavi','vani','swapna'],
                "rollnumber":[401,402,403],
                "branch":["cse","ece","eee"]})

In [6]:
df

name  rollnumber branch
0  vasavi         401    cse
1    vani         402    ece
2  swapna         403    eee

In [9]:
df.loc[2]

name          swapna
rollnumber       403
branch           eee
Name: 2, dtype: object

In [10]:
df.iloc[1]

name          vani
rollnumber     402
branch         ece
Name: 1, dtype: object

In [11]:
df.loc[1]

name          vani
rollnumber     402
branch         ece
Name: 1, dtype: object

In [12]:
df.iloc[2]["branch"]

'eee'

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
name          3 non-null object
rollnumber    3 non-null int64
branch        3 non-null object
dtypes: int64(1), object(2)
memory usage: 152.0+ bytes


In [15]:
df.describe()

rollnumber
count         3.0
mean        402.0
std           1.0
min         401.0
25%         401.5
50%         402.0
75%         402.5
max         403.0

In [16]:
df.count()

name          3
rollnumber    3
branch        3
dtype: int64

In [19]:
df.dtypes

name          object
rollnumber     int64
branch        object
dtype: object

In [23]:
df.count(axis=1)#row count

0    3
1    3
2    3
dtype: int64

In [25]:
df.count(axis=0)#column count

name          3
rollnumber    3
branch        3
dtype: int64

In [27]:
df.count(axis="columns")

0    3
1    3
2    3
dtype: int64

In [28]:
df

name  rollnumber branch
0  vasavi         401    cse
1    vani         402    ece
2  swapna         403    eee

In [30]:
df.set_index(["rollnumber"])

name branch
rollnumber               
401         vasavi    cse
402           vani    ece
403         swapna    eee

In [31]:
df.set_index(["name"])

rollnumber branch
name                     
vasavi         401    cse
vani           402    ece
swapna         403    eee

In [32]:
df.set_index(["name","branch"])

rollnumber
name   branch            
vasavi cse            401
vani   ece            402
swapna eee            403

In [36]:
df1=pd.Series([8,6,5,7,9,3,4,2,"none"])

In [35]:
df1

0       8
1       6
2       5
3       7
4       9
5       3
6       4
7       2
8    none
dtype: object

In [38]:
df1.describe()

count     9
unique    9
top       9
freq      1
dtype: int64

In [39]:
df1.count()

9

In [40]:
import numpy as np


In [47]:
x=np.arange(10)

In [46]:
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
data=pd.DataFrame(np.arange(10).reshape(5,2),columns=['a','b'])

In [58]:
data

a  b
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [59]:
a=np.arange(20)

In [60]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
data1=pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))

In [68]:
data1

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [71]:
data1.loc[1,'b']=np.nan

In [72]:
data1

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [75]:
data1.isnull().sum()

a    0
b    1
c    0
d    0
e    0
dtype: int64

In [83]:
dd=data+data1
dd

a     b   c   d   e
0   0.0   2.0 NaN NaN NaN
1   7.0   NaN NaN NaN NaN
2  14.0  16.0 NaN NaN NaN
3  21.0  23.0 NaN NaN NaN
4   NaN   NaN NaN NaN NaN

In [84]:
dd.fill_values=5

In [85]:
dd

a     b   c   d   e
0   0.0   2.0 NaN NaN NaN
1   7.0   NaN NaN NaN NaN
2  14.0  16.0 NaN NaN NaN
3  21.0  23.0 NaN NaN NaN
4   NaN   NaN NaN NaN NaN

In [90]:
dd.add(data,fill_value=6)

a     b   c   d   e
0   0.0   3.0 NaN NaN NaN
1   9.0   9.0 NaN NaN NaN
2  18.0  21.0 NaN NaN NaN
3  27.0  30.0 NaN NaN NaN
4  14.0  15.0 NaN NaN NaN

In [93]:
np.random.randn(2,5)

array([[-1.37371848,  0.16188865,  0.32184846, -0.17891723, -0.81895246],
       [-0.0808647 ,  0.25177589, -0.45924547, -1.16619304,  0.42319895]])

In [94]:
np.random.rand(2,3)

array([[0.49940998, 0.51439642, 0.55783059],
       [0.05061061, 0.25836752, 0.58549795]])

In [95]:
#creating a data frame with random values
f=pd.DataFrame(np.random.randn(3,4))

In [96]:
f

0         1         2         3
0  1.038119  0.798307 -0.181773  0.900115
1  1.522739 -0.411311 -1.873718 -0.025397
2  0.007871  0.480932  1.660644 -0.437878

In [100]:
#assigning index
f=pd.DataFrame(np.random.randn(3,4),index=['a','b','c'],columns=['s1','s2','s3','s4'])
f

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241

In [108]:
f.index=['a','b','c']

In [109]:
f

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241

In [110]:
#reindexing
f1=f.reindex(['a','b','c','d','e'])
f1

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241
d       NaN       NaN       NaN       NaN
e       NaN       NaN       NaN       NaN

In [112]:
f1.isnull().sum()

s1    2
s2    2
s3    2
s4    2
dtype: int64

In [113]:
#dropping null values

f1.dropna()

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241

In [114]:
# fill the null values with perticular value
f1.fillna(2)

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241
d  2.000000  2.000000  2.000000  2.000000
e  2.000000  2.000000  2.000000  2.000000

In [117]:
f1.fillna(method='bfill',axis=0).fillna(5)#backword fill in this fill the data with given value

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241
d  5.000000  5.000000  5.000000  5.000000
e  5.000000  5.000000  5.000000  5.000000

In [118]:
f1.fillna(method='ffill',axis=0).fillna(5)#forward fill

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241
d -1.449965 -0.801437 -1.140888  0.427241
e -1.449965 -0.801437 -1.140888  0.427241

In [119]:
f1.isnull()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
e   True   True   True   True

In [120]:
f1.isna()

s1     s2     s3     s4
a  False  False  False  False
b  False  False  False  False
c  False  False  False  False
d   True   True   True   True
e   True   True   True   True

In [122]:
pd.isna(f1['s1'])

a    False
b    False
c    False
d     True
e     True
Name: s1, dtype: bool

In [123]:
pd.isna(f1['s4'])

a    False
b    False
c    False
d     True
e     True
Name: s4, dtype: bool

In [124]:
f1

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
b  0.519550  0.144551 -0.479467 -1.117301
c -1.449965 -0.801437 -1.140888  0.427241
d       NaN       NaN       NaN       NaN
e       NaN       NaN       NaN       NaN

In [128]:
#data replacing
f2=pd.DataFrame({'x':[4,5,6],'y':[3,4,5],'z':[8,9,7]})

In [129]:
f2

x  y  z
0  4  3  8
1  5  4  9
2  6  5  7

In [137]:
ff=f1.reindex(['a','d','c'])
ff

s1        s2        s3        s4
a -0.775997 -0.444057  0.030103 -1.917505
d       NaN       NaN       NaN       NaN
c -1.449965 -0.801437 -1.140888  0.427241

In [141]:
ff.sort_index()

s4        s3        s2        s1
a -0.775997 -0.444057  0.030103 -1.917505
c -1.449965 -0.801437 -1.140888  0.427241
d       NaN       NaN       NaN       NaN

In [142]:
fff=ff.columns=['s4','s3','s2','s1']

In [143]:
fff

['s4', 's3', 's2', 's1']

In [144]:
ff.sort_index(axis=1)

s1        s2        s3        s4
a -1.917505  0.030103 -0.444057 -0.775997
d       NaN       NaN       NaN       NaN
c  0.427241 -1.140888 -0.801437 -1.449965

In [145]:
#groupby
animal_df=pd.DataFrame({'name':['dog','cat','dog','cow','cat'],'place':['zoo','ooo','zoo','oo','ooo'],
                       'feature':['s','z','z','a','s']})

In [146]:
animal_df

name place feature
0  dog   zoo       s
1  cat   ooo       z
2  dog   zoo       z
3  cow    oo       a
4  cat   ooo       s

In [147]:
animal_df.groupby('name').count()

place  feature
name                
cat       2        2
cow       1        1
dog       2        2

In [148]:
animal_df.groupby('place').count()

name  feature
place               
oo        1        1
ooo       2        2
zoo       2        2

In [152]:
animal_df.groupby(['name','feature']).sum()

place
name feature      
cat  s         ooo
     z         ooo
cow  a          oo
dog  s         zoo
     z         zoo

In [172]:
#Ranking
ani_df=pd.DataFrame({'name':['dog','cat','dog','cow','cat'],'place':['zoo','ooo','zoo','oo','ooo'],
                       'no_legs':[4,2,3,3,np.nan]})

In [173]:
ani_df

name place  no_legs
0  dog   zoo      4.0
1  cat   ooo      2.0
2  dog   zoo      3.0
3  cow    oo      3.0
4  cat   ooo      NaN

In [174]:
ani_df["rank1"]=ani_df['no_legs'].rank()
ani_df

name place  no_legs  rank1
0  dog   zoo      4.0    4.0
1  cat   ooo      2.0    1.0
2  dog   zoo      3.0    2.5
3  cow    oo      3.0    2.5
4  cat   ooo      NaN    NaN

In [175]:
ani_df["max_rank"]=ani_df['no_legs'].rank(method="max")
ani_df

name place  no_legs  rank1  max_rank
0  dog   zoo      4.0    4.0       4.0
1  cat   ooo      2.0    1.0       1.0
2  dog   zoo      3.0    2.5       3.0
3  cow    oo      3.0    2.5       3.0
4  cat   ooo      NaN    NaN       NaN

In [177]:
ani_df["non_rank"]=ani_df['no_legs'].rank(na_option="bottom")
ani_df

name place  no_legs  rank1  max_rank  first-rank1  non_rank
0  dog   zoo      4.0    4.0       4.0          4.0       4.0
1  cat   ooo      2.0    1.0       1.0          1.0       1.0
2  dog   zoo      3.0    2.5       3.0          2.5       2.5
3  cow    oo      3.0    2.5       3.0          2.5       2.5
4  cat   ooo      NaN    NaN       NaN          5.0       5.0

In [178]:
ani_df["pct_rank"]=ani_df['no_legs'].rank(pct=True)
ani_df

name place  no_legs  rank1  max_rank  first-rank1  non_rank  pct_rank
0  dog   zoo      4.0    4.0       4.0          4.0       4.0     1.000
1  cat   ooo      2.0    1.0       1.0          1.0       1.0     0.250
2  dog   zoo      3.0    2.5       3.0          2.5       2.5     0.625
3  cow    oo      3.0    2.5       3.0          2.5       2.5     0.625
4  cat   ooo      NaN    NaN       NaN          5.0       5.0       NaN

In [179]:
#categarise
data_frame=pd.DataFrame({'x':[1,2,3,4,5],'y':[6,7,8,9,10]})

In [180]:
data_frame

x   y
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [192]:
data_frame["cc"]=data_frame['y'].astype('category')
data_frame

x   y  cc
0  1   6   6
1  2   7   7
2  3   8   8
3  4   9   9
4  5  10  10

In [193]:
data_frame["cc"].cat.categories=["good","bad","worst","verygood","verybad"]
data_frame

x   y        cc
0  1   6      good
1  2   7       bad
2  3   8     worst
3  4   9  verygood
4  5  10   verybad

In [195]:
df=pd.read_table("sample.csv")

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [196]:
df

a b c
0   1 2 3
1  7 8 89

In [197]:
df=pd.read_table("sample.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a b c
0   1 2 3
1  7 8 89

In [199]:
df=pd.read_csv("sample.csv")
df

a b c
0   1 2 3
1  7 8 89

In [203]:
df.head(1)

a b c
0  1 2 3

In [202]:
df.tail(1)

a b c
1  7 8 89

In [206]:
df=pd.read_table("ex1.csv",sep=',')
df

C:\Users\public\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.


a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [207]:
df.head(1)

a  b  c  d message
0  1  2  3  4   hello

In [208]:
df.tail(1)

a   b   c   d message
2  9  10  11  12     foo